common: &common
  adapter: postgresql
  username: postgres
  password: 1Godzilla # from psql setup, see Postgresql
  host: localhost

development:
  <<: *common
  database: zambazu_development

test:
  <<: *common
  database: zambazu_test

production:
  <<: *common
  database: zambazu_production